export const SYLLABUS = {
  physics: {
    name: "Physics",
    color: "blue",
    chapters: [
      { id: "units-dimensions", name: "Units and Dimensions", isNew: true },
      { id: "motion-1d", name: "Motion in One Dimension", isNew: false },
      { id: "motion-2d", name: "Motion in Two Dimensions", isNew: true },
      { id: "laws-of-motion", name: "Laws of Motion", isNew: false },
      { id: "friction", name: "Friction", isNew: false },
      { id: "wpe", name: "Work, Power and Energy", isNew: false },
      { id: "circular-motion", name: "Circular Motion", isNew: false },
      { id: "com", name: "Center of Mass", isNew: false },
      { id: "rotational-motion", name: "Rotational Motion", isNew: false },
      { id: "gravitation", name: "Gravitation", isNew: false },
      { id: "properties-matter", name: "Properties of Matter", isNew: false },
      { id: "fluid-mechanics", name: "Fluid Mechanics", isNew: false },
      { id: "thermal-properties", name: "Thermal Properties of Matter", isNew: false },
      { id: "thermodynamics", name: "Thermodynamics", isNew: false },
      { id: "ktg", name: "Kinetic Theory of Gases", isNew: false },
      { id: "shm", name: "Oscillations (SHM)", isNew: false },
      { id: "waves-sound", name: "Waves and Sound", isNew: false },
      { id: "electrostatics", name: "Electrostatics", isNew: false },
      { id: "capacitance", name: "Capacitance", isNew: false },
      { id: "current-electricity", name: "Current Electricity", isNew: false },
      { id: "magnetic-effects", name: "Magnetic Effects of Current", isNew: false },
      { id: "magnetism-matter", name: "Magnetism and Matter", isNew: false },
      { id: "emi", name: "Electromagnetic Induction", isNew: false },
      { id: "ac", name: "Alternating Current", isNew: false },
      { id: "em-waves", name: "Electromagnetic Waves", isNew: false },
      { id: "ray-optics", name: "Ray Optics", isNew: false },
      { id: "wave-optics", name: "Wave Optics", isNew: false },
      { id: "dual-nature", name: "Dual Nature of Matter", isNew: false },
      { id: "atoms-nuclei", name: "Atoms and Nuclei", isNew: false },
      { id: "semiconductors", name: "Semiconductors", isNew: false },
      { id: "communication-systems", name: "Communication Systems", isNew: false },
    ]
  },
  chemistry: {
    name: "Chemistry",
    color: "emerald",
    chapters: [
      { id: "mole-concept", name: "Mole Concept", isNew: false },
      { id: "atomic-structure", name: "Atomic Structure", isNew: false },
      { id: "states-of-matter", name: "States of Matter", isNew: false },
      { id: "thermodynamics", name: "Thermodynamics", isNew: false },
      { id: "chemical-equilibrium", name: "Chemical Equilibrium", isNew: false },
      { id: "ionic-equilibrium", name: "Ionic Equilibrium", isNew: false },
      { id: "redox", name: "Redox Reactions", isNew: false },
      { id: "electrochemistry", name: "Electrochemistry", isNew: false },
      { id: "kinetics", name: "Chemical Kinetics", isNew: false },
      { id: "surface-chemistry", name: "Surface Chemistry", isNew: false },
      { id: "solutions", name: "Solutions", isNew: false },
      { id: "solid-state", name: "Solid State", isNew: false },
      { id: "periodic-table", name: "Periodic Table", isNew: false },
      { id: "chemical-bonding", name: "Chemical Bonding", isNew: false },
      { id: "hydrogen", name: "Hydrogen", isNew: false },
      { id: "s-block", name: "s-Block Elements", isNew: false },
      { id: "p-block", name: "p-Block Elements", isNew: false },
      { id: "d-f-block", name: "d and f Block Elements", isNew: false },
      { id: "coordination", name: "Coordination Compounds", isNew: false },
      { id: "metallurgy", name: "Metallurgy", isNew: false },
      { id: "environmental", name: "Environmental Chemistry", isNew: false },
      { id: "goc", name: "General Organic Chemistry (GOC)", isNew: true },
      { id: "hydrocarbons", name: "Hydrocarbons", isNew: false },
      { id: "haloalkanes", name: "Haloalkanes and Haloarenes", isNew: false },
      { id: "alcohols-phenols", name: "Alcohols, Phenols and Ethers", isNew: false },
      { id: "carbonyls", name: "Aldehydes, Ketones and Carboxylic Acids", isNew: false },
      { id: "amines", name: "Amines", isNew: false },
      { id: "biomolecules", name: "Biomolecules", isNew: false },
      { id: "polymers", name: "Polymers", isNew: false },
      { id: "everyday-chem", name: "Chemistry in Everyday Life", isNew: false },
      { id: "practical-organic", name: "Practical Organic Chemistry", isNew: false },
    ]
  },
  mathematics: {
    name: "Mathematics",
    color: "purple",
    chapters: [
      { id: "sets", name: "Sets", isNew: false },
      { id: "relations-functions", name: "Relations and Functions", isNew: false },
      { id: "trig-functions", name: "Trigonometric Functions", isNew: false },
      { id: "inverse-trig", name: "Inverse Trigonometric Functions", isNew: false },
      { id: "complex-numbers", name: "Complex Numbers", isNew: false },
      { id: "quadratic", name: "Quadratic Equations", isNew: false },
      { id: "sequence-series", name: "Sequence and Series", isNew: false },
      { id: "pnc", name: "Permutations and Combinations", isNew: false },
      { id: "binomial", name: "Binomial Theorem", isNew: false },
      { id: "probability", name: "Probability", isNew: false },
      { id: "matrices", name: "Matrices", isNew: true },
      { id: "determinants", name: "Determinants", isNew: false },
      { id: "limits", name: "Limits", isNew: false },
      { id: "continuity-diff", name: "Continuity and Differentiability", isNew: false },
      { id: "differentiation", name: "Differentiation", isNew: false },
      { id: "aod", name: "Applications of Derivatives", isNew: false },
      { id: "indefinite-integration", name: "Indefinite Integration", isNew: false },
      { id: "definite-integration", name: "Definite Integration", isNew: false },
      { id: "differential-equations", name: "Differential Equations", isNew: false },
      { id: "vector-algebra", name: "Vector Algebra", isNew: false },
      { id: "3d-geometry", name: "3D Geometry", isNew: false },
      { id: "straight-lines", name: "Straight Lines", isNew: false },
      { id: "circles", name: "Circles", isNew: false },
      { id: "parabola", name: "Parabola", isNew: false },
      { id: "ellipse", name: "Ellipse", isNew: false },
      { id: "hyperbola", name: "Hyperbola", isNew: false },
      { id: "statistics", name: "Statistics", isNew: false },
      { id: "reasoning", name: "Mathematical Reasoning", isNew: false },
      { id: "height-distance", name: "Height and Distance", isNew: false },
    ]
  }
};
